s=set([1,2,3,2,3,1,4])
print(s)
s1={'python',1,2}
print(s1)
print(type(s1))
s.add('python')
s.pop()#删除第一个元素
print(s)
s.remove(4)#删除指定元素，等于s.discard(4),但若没有这个元素不报错(None)
print(s)
f=frozenset('qiwer')#不可变集合
print(f)
b1=['name',123,['python','php']]
b2=b1.copy()
print(b1)
print(b2)#两个列表不相等但里面元素相等
b1[0]=100
print(b1)
print(b2)
b1[2][0]=99
print(b1)
print(b2)#只复制第一层深层不复制
import copy
b3=copy.deepcopy(b1)
b1[2][0]='java'
print(b1)
print(b3)
#&交集｜并集-两集相减round(a,2):a保留俩位小数ord()阿瑟课吗chr()阿萨克嘛转字符
